version: "3.7"

services:
  frontend:
    image: ghcr.io/bizinmitya/front-react-avito:v1.17
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./
    ports:
      - "8080:8080"